---
title: "Fakeblog"
date: 2018-08-18
---

title: Music Rules 
author: Rachel Miles
email: milesrachel9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is here to help people understand why music is so great. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
